services:
  grafana:
    build: ./grafana
    ports:
    - 3000:3000
  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    build: ./ingester
    environment:
      - ZIP_FILE_PATH=/export.zip  # This will be set dynamically
      - USER_ID=Vibhu  # This will be set dynamically
    volumes:
    - ./tests/export.zip:/export.zip

volumes:
  influx-data: